# fly.toml app configuration file generated for ethdam-2024 on 2024-04-14T07:14:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ethdam-2024'
primary_region = 'ams'
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
